### ISSUE TITLE
Min API Support

### ISSUE THREAD

**Issue by ligol** [tvbarthel/BlurDialogFragment#21]
Hey,

Is it normal that min api is now at 14?
After a check, I don't see any mention in changelog, does this choice is due to a technical issue?

**Comment by tbarthel-fr** [comment]
Hey (=

First of all, I'm really sorry for this late answer, I should have check issues much sooner...

The min api was fixed at 14 for the 1.0.0 release as we use .animate() framework to fade in the blurred background. Moreover, version under 14/15 shouldn't be supported for new apps.

A simple check on the version would allow a min api 9 back (blur effect won't be animated I will take a look asap (:

**Comment by ligol** [comment]
Thank for your answer, if I have the time, I will check and try, and maybe make a pull request.

**Comment by ligol** [comment]
Hey,

I made a Pull request #22 with the support in Min API 9 and RenderScript support v8.

**Comment by tbarthel-fr** [comment]
Your work has just been merged, v2.0.0 is now available (= (sample app update should be available in couple hours)
https://github.com/tvbarthel/BlurDialogFragment/releases/tag/v2.0.0
