### ISSUE TITLE
Can't use without inheritance since BlurDialogEngine is now package-private

### ISSUE THREAD

**Issue by sergiopantoja** [tvbarthel/BlurDialogFragment#23]
Great library!

I see that commit [be45e05afb989a040b49cdaffce2d439cf27475c](https://github.com/tvbarthel/BlurDialogFragment/commit/be45e05afb989a040b49cdaffce2d439cf27475c) made BlurDialogEngine a package-private class, which means we can't use this library without inheritance. Is this a bug or does [this section](https://github.com/tvbarthel/BlurDialogFragment#avoiding-inheritance) of the README not apply for version 2.0.0?

Thanks,
Sergio

**Comment by vbarthel-fr** [comment]
Oups, that was not expected. Sorry about that, it will be corrected asap.

**Comment by tbarthel-fr** [comment]
Thanks again for reporting it (=

Commit 5d1a3a5bb1fa779c8bf809a3122fc1ce143bd211 must restore the usage of BlurDialogEngine.

**Comment by sergiopantoja** [comment]
Awesome! Thanks for the quick fix! :smile:
