### ISSUE TITLE
FastBlurHelper won't use RenderScript below API 16

### ISSUE THREAD

**Issue by jacobtabak** [tvbarthel/BlurDialogFragment#27]
Due to [this line of code](https://github.com/tvbarthel/BlurDialogFragment/blob/master/lib/src/main/java/fr/tvbarthel/lib/blurdialogfragment/FastBlurHelper.java#L63), RenderScript won't be used below API 16.  Is that intentional?

**Comment by tbarthel-fr** [comment]
It appears that we forgot to remove this restriction when support.v8.renderscript was added :x

**Comment by tbarthel-fr** [comment]
It should be fixed by 2d6beb50d385a8128bb7a667d92adc474bbcd064 One more time thanks a lot!

I will try to publish a new release with the support of the new AppCompatActivity this week.
