### ISSUE TITLE
isStatusBarTranslucent doesn't work well

### ISSUE THREAD

**Issue by wangsai-silence** [tvbarthel/BlurDialogFragment#30]
I have set my activity's statusbar translucent,but it seems the method isStatusBarTranslucent can not judge out.  

PS: why add margins when bluring? I am confused about that. Hope for your answer.

**Comment by tbarthel-fr** [comment]
Hi @wangsai-silence (=

You'r right, the top margin should definitively be replaced by a top offset decrease of the src image. This will blur the pixels "bellow" the status when isStatusBarTranslucent is turned on.

I try to solve two other issues that bother me asap and I will publish a new release including this fix (:

**Comment by tbarthel-fr** [comment]
The last release available on maven central (check readme update) should fix the support of a translucent status bar. @1f3baa599f1bc90e8a437b9f30a90c5c5d8a4d29

![device-2015-05-10-115208](https://cloud.githubusercontent.com/assets/4211470/7553890/f825f730-f70e-11e4-906b-be3a83625950.png)


![device-2015-05-10-114922](https://cloud.githubusercontent.com/assets/4211470/7553891/fb917df4-f70e-11e4-86b0-ee3b20b3a580.png)


Thanks a lot for your report and your interest in this project (=
