### ISSUE TITLE
Does the lib realy need android.png ressource

### ISSUE THREAD

**Issue by ligol** [tvbarthel/BlurDialogFragment#33]
Can we remove the android.png ressource from the aar push on JCenter?

**Comment by tbarthel-fr** [comment]
As it's no longer being used it won't be a problem (x

I'm really sorry for this oversight, should definitivelly turn abortOnError to true in lintOptions...

gonna try to publish a new release asap, I'll come back to you when it will be done.

Thanks a lot for your report! (:

**Comment by tbarthel-fr** [comment]
Successfully synced on maven central : v2.1.3

The size of the aar is cut by 95% I'm so ashamed... Let says that it's my first library (x

One more time thanks a lot @ligol !
