### ISSUE TITLE
Blur Background goes up.

### ISSUE THREAD

**Issue by Vram-Voskanyan** [tvbarthel/BlurDialogFragment#35]
Hello,

First of all thanks for awesome library, and sorry for my English.

I have bug on Nexus 5 running a 5.1.1 .
In all cases background view goes up. Here are screenshots from your app:
![1](https://cloud.githubusercontent.com/assets/5053313/8160999/d67ac4e8-1384-11e5-8aa9-ff1a9053d069.png)
![2](https://cloud.githubusercontent.com/assets/5053313/8161005/e7a86ca2-1384-11e5-8db0-c9d01e8f4465.jpg)

Regards

**Comment by tbarthel-fr** [comment]
Hi @Vram-Voskanyan (:

Thanks for your interest in our project!

We should definitively update the sample app with the last library version (x

I will update the sample app tomorrow and come back to you when it's done (:

Best Regards,

Thomas.

**Comment by tbarthel-fr** [comment]
@Vram-Voskanyan 

The sample app has been updated with the last library version, it works like a charm on my N5 5.1.1.

It should be the same on your side (=

Best regards,

Thomas.

**Comment by Vram-Voskanyan** [comment]
Yeah it is really nice in our side too.

Best regards,
Vram
