### ISSUE TITLE
How to implement a bottom sheet dialog with blur behind?

### ISSUE THREAD

**Issue by mori-honest** [tvbarthel/BlurDialogFragment#37]
How to implement a [ bottom sheet](https://www.google.com/design/spec/components/bottom-sheets.html#) with blur behind?

**Comment by vbarthel-fr** [comment]
Hi @mori-honest, a bottom sheet might be implemented as a dialog fragment with a custom style/view. 

What you could try is:
* Extend DialogFragment
* Return a View representing the desired view in the [DialogFragment#onCreateView](http://developer.android.com/reference/android/app/Fragment.html#onCreateView(android.view.LayoutInflater, android.view.ViewGroup, android.os.Bundle))
* Use the [BlurEngine](https://github.com/tvbarthel/BlurDialogFragment#avoiding-inheritance) to get the blur effect.

If I have some times in the coming days, I will try to implement it.

Have a nice day & happy coding (:
