### ISSUE TITLE
allowBackup="true"

### ISSUE THREAD

**Issue by edward-s** [tvbarthel/BlurDialogFragment#38]
Hi,

is there any reason why you are setting the allowBackup to true in the AndroidManifest.xml?

company policy requires me to set this flag as false

**Comment by vbarthel-fr** [comment]
Nice catch !

We will set the allowBackup attribute to false in the next release.

Thanks =)

**Comment by edward-s** [comment]
thank you
looking forward to it

**Comment by vbarthel-fr** [comment]
Hi @edward-s 

I did not have the time to update the library, but here is a solution to set the allowBackup flag to false. It simply relies on the "replace" attributs:

```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest
    package="com.your.package"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools">

    <application
        android:allowBackup="false"
        tools:replace="allowBackup">

        ...

    </application>


</manifest>
```

I have just tested this solution on one of my project, and it seems to work perfectly. Please let me know if this also works for you =)

Happy coding,

Vincent.
