### ISSUE TITLE
How to make the dialog background transparent?

### ISSUE THREAD

**Issue by mori-honest** [tvbarthel/BlurDialogFragment#41]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="wrap_content"
              android:layout_height="wrap_content"
              android:background="@android:color/transparent"
              android:gravity="center"
              android:orientation="vertical">

       <Button
        android:id="@id/cancelButton"
        android:layout_width="300dp"
        android:layout_height="50dp"
        android:layout_alignParentBottom="true"
        android:layout_centerHorizontal="true"
        android:layout_margin="10dp"
        android:background="@drawable/btn_morning_bg_blue"
        android:text="@string/cancel"
        android:textColor="@android:color/white"/>
      </LinearLayout>

I set the background of parent layout to transparent but i get this:
![screen shot 1394-05-14 at 10 24 19](https://cloud.githubusercontent.com/assets/5219339/9079198/cf83c8ce-3b5c-11e5-8cdf-034c66a16d55.png)

**Comment by sumy7** [comment]
you can try 

    getDialog().getWindow().setBackgroundDrawableResource(android.R.color.transparent);

**Comment by tbarthel-fr** [comment]
Hi (:

As @sumy7 mentionned, even if your layout background is transparent, the background of the window will still be displayed.

Just set the background of the dialog to transparent before calling .show().

Keep in mind that a transparent dialog background might reduce the emphasis on the dialog content, which is what this library is trying to enforce (=

**Comment by mori-honest** [comment]
I Tried @sumy7 's answer but it works on some devices running android 5.0 only!
I get the same result shown in my question in other devices running 4.4.4 or 4.1.

**Comment by mfloresblanco** [comment]
chek out this example for blur effect with transparent background:
public class Dialog_exit_from_lesson extends BlurDialogFragment 
{
	

	Button yes,no;

    public static Dialog_exit_from_lesson newInstance() {
        Dialog_exit_from_lesson fragment = new Dialog_exit_from_lesson();
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
		
    }

    @NonNull
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        final Dialog dialog = new Dialog(getActivity());
		dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);
		dialog.getWindow().setBackgroundDrawable(new ColorDrawable(android.graphics.Color.TRANSPARENT));
		dialog.setContentView(R.layout.dialog_exit_from_lesson);
		dialog.show();
		return dialog;
		
	}

    @Override
    protected boolean isDebugEnable() {
        return false;
    }

    @Override
    protected boolean isDimmingEnable() {
        return true;
    }

    @Override
    protected boolean isActionBarBlurred() {
        return true;
    }

    @Override
    protected float getDownScaleFactor() {
        return 8;
    }

    @Override
    protected int getBlurRadius() {
        return 8;
    }
	
}

**Comment by mfloresblanco** [comment]
I achieved the transparent background but I can't seem how to implement onClickListener for buttons, any idea?

**Comment by mfloresblanco** [comment]
well i found a way to set it transparent and onclick listener working. here the example, also have on mind to create a custom xml dialog 



public class Dialog_exit_from_lesson extends BlurDialogFragment 
{
Button yes,no;

    public static Dialog_exit_from_lesson newInstance() {
        Dialog_exit_from_lesson fragment = new Dialog_exit_from_lesson();
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
		
    }

    @NonNull
    @Override
    public Dialog onCreateDialog(Bundle savedInstanceState) {
        final Dialog dialog = new Dialog(getActivity());
		dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);
		dialog.getWindow().setBackgroundDrawable(new ColorDrawable(android.graphics.Color.TRANSPARENT));
		dialog.setContentView(R.layout.dialog_exit_from_lesson);
		dialog.create();
		yes=(Button)dialog.findViewById(R.id.btn_yes);
		no=(Button)dialog.findViewById(R.id.btn_no);
		yes.setOnClickListener(new View.OnClickListener(){

				@Override
				public void onClick(View p1)
				{
					Intent upIntent = NavUtils.getParentActivityIntent(getActivity());
					NavUtils.navigateUpTo(getActivity(), upIntent);
				}
			});
		no.setOnClickListener(new View.OnClickListener(){

				@Override
				public void onClick(View p1)
				{
					dialog.dismiss();
					// TODO: Implement this method
				}
			});
		
		return dialog;
	}

    @Override
    protected boolean isDebugEnable() {
        return false;
    }

    @Override
    protected boolean isDimmingEnable() {
        return true;
    }

    @Override
    protected boolean isActionBarBlurred() {
        return true;
    }

    @Override
    protected float getDownScaleFactor() {
        return 8;
    }

    @Override
    protected int getBlurRadius() {
        return 8;
    }
	










remember to launch the dialog this way:
public void onClearClick(View v)
	{
		Dialog_exit_from_lesson fragment
		= Dialog_exit_from_lesson.newInstance();
		fragment.show(getFragmentManager(), "blur_sample");
	}
