### ISSUE TITLE
On orientation change dialogFragment with setRetainInstance(true) the blur background disappear

### ISSUE THREAD

**Issue by IskuhiSargsyan** [tvbarthel/BlurDialogFragment#56]
I use setRetaineInstance(true) in DialogFragment,while on orientation change ,the blur background is disappeared.

**Comment by tbarthel-fr** [comment]
fix submitted https://github.com/tvbarthel/BlurDialogFragment/pull/58

should be integrated in the next release.

**Comment by tbarthel-fr** [comment]
@IskuhiSargsyan version 2.1.6 is live and must integrate the fix.

Thanks a lot for your report (=
