### ISSUE TITLE
Is there any way to have a transparent DialogFragment for Pre-Lollipop?

### ISSUE THREAD

**Issue by amanzan** [tvbarthel/BlurDialogFragment#68]
I tried everything I found on stackoverflow regarding this and nothing works so far for Pre-Lollipop. This is the closest I get to transparency (note I am also using BlurDialogFragment library):
![l9ii_open_eukot49i d60520halberto11202016123508](https://cloud.githubusercontent.com/assets/3911627/20462439/4803a2e8-af1e-11e6-98b0-cefffcdca491.png)

I am using a custom style:
`    <style name="MyTransparentDialog" parent="Theme.AppCompat.Light.Dialog">
        <item name="android:windowBackground">@android:color/transparent</item>
        <item name="android:windowIsFloating">true</item>
        <item name="android:windowIsTranslucent">true</item>
    </style>`

And setting it like this in onCreateDialog method:
`AlertDialog.Builder builder = new AlertDialog.Builder(getActivity(), R.style.MyTransparentDialog);`

**Comment by tbarthel-fr** [comment]
Hi @amanzan (=

it reminds me a closed issue where a dev posted his trick to perform what you are looking for.

Have you try it on your side?

https://github.com/tvbarthel/BlurDialogFragment/issues/41#issuecomment-186664388
