### ISSUE TITLE
Caused by java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by huytower** [tvbarthel/BlurDialogFragment#70]
Last week my project got many crash and I saw below exception, 
It looks like related to your library project,

> Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
>        at android.os.AsyncTask$3.done(AsyncTask.java:300)
>        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
>        at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
>        at java.lang.Thread.run(Thread.java:841)
> Caused by java.lang.ArrayIndexOutOfBoundsException: length=20736; index=21079
>        at fr.tvbarthel.lib.blurdialogfragment.FastBlurHelper.doBlur(FastBlurHelper.java:132)
>        at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine.blur(BlurDialogEngine.java:396)
>        at fr.tvbarthel.lib.blurdialogfragment.BlurDialogEngine.access$100(BlurDialogEngine.java:41)

You can help me to check to avoid this crash?
Thank you so much,

**Comment by tbarthel-fr** [comment]
Hi @huytower 

Thanks for you interest in this project (=

I only reproduce it on an emulator for a reason I didn't get yet :/ 

By any chances, do you have the physical device model on which this exception is raised?

**Comment by huytower** [comment]
Hello, I often get this crash since I use old library before October last year.
Can not find any crash since use latest library.

Thank you so much :)

**Comment by vbarthel-fr** [comment]
Good news!! Thanks for keeping us updated about this issue =)

Happy to see that the latest version solved your problem!
